version "4.5"

#include "ZSCRIPT.SpellBrain.zsc"
#include "ZSCRIPT.ArcanumSpell.zsc"
#include "ZSCRIPT.ArcanumSigil.zsc"
#include "ZSCRIPT.ArcanumTome.zsc"

class ArcanumHandler : EventHandler
{
	override void CheckReplacement(ReplaceEvent e)
	{
		if (!e.Replacement)
		{
			return;
		}

		switch (e.Replacement.GetClassName())
		{
			case 'Lumberjack':
				if (random[arcanrand]() <= 64)
				{
					e.Replacement = "HDArcanumTome";
				}
				break;
		}
	}

	override void PlayerEntered(PlayerEvent e)
	{
		ArcanumSpellBrain Brain = ArcanumSpellBrain.Get(e.PlayerNumber);
		Brain.InitSpells(); // [Ace] Because PostBeginPlay seems to be called a bit too late on it. In fact, it doesn't seem to be called at all.
	}

	override void NetworkProcess(ConsoleEvent e)
	{
		if (e.Name ~== "ARC_ReInitSpells")
		{
			ArcanumSpellBrain Brain = ArcanumSpellBrain.Get(e.Player);
			Brain.InitSpells();
		}
	}
}

// --------------------------------------------------
// DEBUG & MISC
// --------------------------------------------------

class ArcanumMath
{
	const Pi = 3.14159;
}