version "4.5"

#include "zscript/accensus/arcanum/Spells/Destruction/Fireball.zsc"
#include "zscript/accensus/arcanum/Spells/Destruction/Claymore.zsc"
#include "zscript/accensus/arcanum/Spells/Destruction/Thunderclap.zsc"
#include "zscript/accensus/arcanum/Spells/Destruction/Hammerfist.zsc"
#include "zscript/accensus/arcanum/Spells/Destruction/Immolation.zsc"
#include "zscript/accensus/arcanum/Spells/Destruction/Voidstorm.zsc"

#include "zscript/accensus/arcanum/Spells/Restoration/Revitalization.zsc"
#include "zscript/accensus/arcanum/Spells/Restoration/LifeForce.zsc"
#include "zscript/accensus/arcanum/Spells/Restoration/Rage.zsc"
#include "zscript/accensus/arcanum/Spells/Restoration/Transfusion.zsc"
#include "zscript/accensus/arcanum/Spells/Restoration/Resurrect.zsc"
#include "zscript/accensus/arcanum/Spells/Restoration/SoulGuard.zsc"
#include "zscript/accensus/arcanum/Spells/Restoration/Invulnerability.zsc"

#include "zscript/accensus/arcanum/Spells/Alteration/FarReach.zsc"
#include "zscript/accensus/arcanum/Spells/Alteration/Worldbreaker.zsc"
#include "zscript/accensus/arcanum/Spells/Alteration/Shield.zsc"
#include "zscript/accensus/arcanum/Spells/Alteration/Haste.zsc"
#include "zscript/accensus/arcanum/Spells/Alteration/HoradricMalus.zsc"
#include "zscript/accensus/arcanum/Spells/Alteration/Feather.zsc"
#include "zscript/accensus/arcanum/Spells/Alteration/Reenergize.zsc"
#include "zscript/accensus/arcanum/Spells/Alteration/Displacement.zsc"
#include "zscript/accensus/arcanum/Spells/Alteration/MassRecall.zsc"

#include "zscript/accensus/arcanum/Spells/Conjuration/GuardianOrb.zsc"
#include "zscript/accensus/arcanum/Spells/Conjuration/GhostSquad.zsc"
#include "zscript/accensus/arcanum/Spells/Conjuration/HolyForce.zsc"
#include "zscript/accensus/arcanum/Spells/Conjuration/Barrier.zsc"
#include "zscript/accensus/arcanum/Spells/Conjuration/Bridge.zsc"
#include "zscript/accensus/arcanum/Spells/Conjuration/Candlelight.zsc"

#include "zscript/accensus/arcanum/SpellBrain.zsc"
#include "zscript/accensus/arcanum/ArcanumSpell.zsc"
#include "zscript/accensus/arcanum/ArcanumSigil.zsc"
#include "zscript/accensus/arcanum/ArcanumTome.zsc"
#include "zscript/accensus/arcanum/ManaBarrel.zsc"

#include "zscript/accensus/arcanum/handlers/ArcanumHandler.zsc"

// --------------------------------------------------
// DEBUG & MISC
// --------------------------------------------------

class ArcanumMath
{
	const Pi = 3.14159;
}